/* Generated By:JJTree: Do not edit this line. DCL_BuiltinFunc.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=DCL_,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.piax.common.dcl.parser;

public
@SuppressWarnings("all")
class DCL_BuiltinFunc extends SimpleNode {
  public DCL_BuiltinFunc(int id) {
    super(id);
  }

  public DCL_BuiltinFunc(DCLParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(DCLParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=b7afd4a8c8e1a15e47d0f1e5f6bec33f (do not edit this line) */
