/* Generated By:JJTree: Do not edit this line. DCL_MinusNumber.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=DCL_,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.piax.common.dcl.parser;

public
@SuppressWarnings("all")
class DCL_MinusNumber extends SimpleNode {
  public DCL_MinusNumber(int id) {
    super(id);
  }

  public DCL_MinusNumber(DCLParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(DCLParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=3974695cc730813caecba8233633c2b1 (do not edit this line) */
