/* Generated By:JavaCC: Do not edit this line. DCLParserTreeConstants.java Version 5.0 */
package org.piax.common.dcl.parser;

@SuppressWarnings("all")
public interface DCLParserTreeConstants
{
  public int JJTSTARTDESTINATION = 0;
  public int JJTDESTINATION = 1;
  public int JJTSTARTDCL = 2;
  public int JJTANDCONDITION = 3;
  public int JJTPREDICATE = 4;
  public int JJTVAR = 5;
  public int JJTVOID = 6;
  public int JJTENUMERATION = 7;
  public int JJTINTERVAL = 8;
  public int JJTBETWEEN = 9;
  public int JJTBUILTINFUNC = 10;
  public int JJTMINUSNUMBER = 11;
  public int JJTINTEGER = 12;
  public int JJTFLOATING = 13;
  public int JJTSTRING = 14;


  public String[] jjtNodeName = {
    "StartDestination",
    "Destination",
    "StartDCL",
    "AndCondition",
    "Predicate",
    "Var",
    "void",
    "Enumeration",
    "Interval",
    "Between",
    "BuiltinFunc",
    "MinusNumber",
    "Integer",
    "Floating",
    "String",
  };
}
/* JavaCC - OriginalChecksum=9abf2362570e0e00e567665ccd071835 (do not edit this line) */
