/* Generated By:JavaCC: Do not edit this line. DCLParserVisitor.java Version 5.0 */
package org.piax.common.dcl.parser;

@SuppressWarnings("all")
public interface DCLParserVisitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(DCL_StartDestination node, Object data);
  public Object visit(DCL_Destination node, Object data);
  public Object visit(DCL_StartDCL node, Object data);
  public Object visit(DCL_AndCondition node, Object data);
  public Object visit(DCL_Predicate node, Object data);
  public Object visit(DCL_Var node, Object data);
  public Object visit(DCL_Enumeration node, Object data);
  public Object visit(DCL_Interval node, Object data);
  public Object visit(DCL_Between node, Object data);
  public Object visit(DCL_BuiltinFunc node, Object data);
  public Object visit(DCL_MinusNumber node, Object data);
  public Object visit(DCL_Integer node, Object data);
  public Object visit(DCL_Floating node, Object data);
  public Object visit(DCL_String node, Object data);
}
/* JavaCC - OriginalChecksum=3c2aa6b1e9a148be855c46c4a3bc2e4a (do not edit this line) */
